const AppState = {

	userName: 'Prof. Chiranjeev Kumar',
	inputId: '',
	invalidInputFlag: false,
	searchStudentDisplayFlag: true,
	studentDetailsDisplayFlag: false,
	courseDetailsDisplayFlag: false,
	currentRegistrationDisplayFlag: false,
	phdProgressReportDisplayFlag: false,
	comprehensiveExaminationDisplayFlag: false,
	presubmissionDisplayFlag: false,
	researchProposalDisplayFlag: false,
	jrfToSrfDisplayFlag: false,
	vivaVoceDisplayFlag: false,
	synopsysAndDraftThesisDisplayFlag: false,
	finalThesisDisplayFlag: false,
	studentDetails: '',
	courseDetails: '',
	currentRegistration: '',
	comprehensiveExaminationStatus: '',
	researchProposalStatus: '',
	jrfToSrfStatus: '',
	presubmissionStatus: '',
	vivaVoceStatus: '',
	synopsysStatus: '',
	draftThesisStatus: '',
	finalThesisStatus: '',
	comprehensiveExaminationDetails: {},
	researchProposalDetails: {},
	jrfToSrfDetails: {},
	presubmissionDetails: {},
	vivaVoceDetails: {},
	synopsysDetails: {},
	draftThesisDetails: {},
	finalThesisDetails: {}
};

export default AppState;
